PATHS:
  # Results output folder
  RESULTS: './results' 
  # Path to where the dataset is stored
  DATASET: '/path/to/the/dataset'
  # Path to where calibration files are stored
  DATASET_CALIB: '/path/to/the/dataset/calibration'
  # Path to where the segmentation predictions are stored
  SEGMENTATIONS: '/path/to/the/prediciton/root'

SEGMENTATIONS:
  # Prediciton dir structure:
  #  - False: pred_dir/method/sequence/frame.png
  #  - True:  pred_dir/sequence/method/frame.png
  SEQ_FIRST: False
  # Specify which colors are used in segmentation maps
  INPUT_COLORS: 
    - [247, 195,  37] # Obstacle
    - [ 41, 167, 224] # Water
    - [ 90,  75, 164] # Sky
